services:
    app:
        image: ghcr.io/andrzejskowron/byos_laravel:skip-failed-polling
        ports:
            - "4567:8080"
        environment:
            #- APP_KEY=
            - PHP_OPCACHE_ENABLE=1
            - TRMNL_PROXY_REFRESH_MINUTES=15
            - DB_DATABASE=database/storage/database.sqlite
        volumes:
            - database:/var/www/html/database/storage
            - storage:/var/www/html/storage/app/public/images/generated
        restart: unless-stopped
volumes:
    database:
    storage:
